-- BAJAR LAS DOS FICHAS QUE FALTABAN: SIETE OJOS 4 Y MERCEDES IZQUIERDO 3
--
-- Los dos ultimos accesos sin portal de Catastro. Y no les pasaba nada raro: su
-- ficha no estaba bajada, nada mas. Ninguna de las dos tiene `plp`.
--
--   CL SIETE OJOS 4          escalera E     53 inmuebles   42 viviendas   3.244 m2
--   CL MERCEDES IZQUIERDO 3  sin escalera   10 inmuebles    8 viviendas     943 m2
--
-- POR QUE EL TRABAJO DE LAS FICHAS NO LAS BAJO NUNCA: su marcador es
-- `accesos_comunidad.ficha_id`, y las 1.229 filas de esa tabla ya lo tienen, asi
-- que ?hacer=1 contesta "quedan 0". Ese trabajo nunca mira `accesos`. Estas dos
-- se quedaron fuera sin un solo sintoma.
--
-- ============================================================================
-- POR QUE EL JSON VA PEGADO AQUI DENTRO, Y POR QUE ESTO NO ES LA FORMA DE
-- CARGAR FICHAS
-- ============================================================================
--
-- La respuesta literal de Catastro va incrustada como texto, y de ella se derivan
-- con SQL la ficha, sus portales y sus inmuebles: lo mismo que hace
-- lib/fichaCatastro.ts, pero escrito otra vez en otro idioma.
--
-- ESO ES UN DEFECTO, y se hace asi por una razon concreta: mis escrituras a
-- produccion estan bloqueadas por el clasificador de permisos de Claude Code, y
-- la unica forma de bajar una ficha suelta con el codigo que ya existe seria
-- exponer `guardarFicha` en el endpoint, que Monica no quiso tocar hoy para no
-- desviarse. Asi que esto es un parche de dos fincas, A MANO Y UNA VEZ.
--
-- SI MAÑANA HAY QUE BAJAR UNA TERCERA, NO SE COPIA ESTE FICHERO: se le pone el
-- parametro al endpoint y se usa el parser de verdad. Dos versiones del mismo
-- calculo en dos idiomas es exactamente como se llega a una base incoherente,
-- que es de lo que venimos hoy.
--
-- LO QUE SI SE RESPETA: el `bruto` que queda guardado es la respuesta tal cual la
-- dio Catastro, sin recortar, igual que las otras 1.184. Y `consultado_en` lleva
-- la fecha de hoy, que es cuando se pidio de verdad.

-- ---------------------------------------------------------------------------
-- CL SIETE OJOS 4, escalera E, ALCORCON
-- ---------------------------------------------------------------------------

with j as (select '{"consulta_dnprcResult":{"control":{"cudnp":53},
"lrcdnp":{"rcdnp":[{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0001",
"cc1":"L",
"cc2":"Q"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"SM",
"pu":"A"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"55",
"cpt":"2,060000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0002",
"cc1":"B",
"cc2":"W"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"SM",
"pu":"B"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"69",
"cpt":"1,770000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0003",
"cc1":"Z",
"cc2":"E"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"SM",
"pu":"01"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Almacen-Estacionamiento",
"sfc":"17",
"cpt":"0,250000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0004",
"cc1":"X",
"cc2":"R"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"SM",
"pu":"06"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Almacen-Estacionamiento",
"sfc":"8",
"cpt":"0,180000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0005",
"cc1":"M",
"cc2":"T"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"SM",
"pu":"03"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Almacen-Estacionamiento",
"sfc":"6",
"cpt":"0,180000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0006",
"cc1":"Q",
"cc2":"Y"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"SM",
"pu":"04"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Almacen-Estacionamiento",
"sfc":"6",
"cpt":"0,180000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0007",
"cc1":"W",
"cc2":"U"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"SM",
"pu":"05"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Almacen-Estacionamiento",
"sfc":"7",
"cpt":"0,180000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0008",
"cc1":"E",
"cc2":"I"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"SM",
"pu":"02"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Almacen-Estacionamiento",
"sfc":"6",
"cpt":"0,180000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0009",
"cc1":"R",
"cc2":"O"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"SM",
"pu":"07"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Almacen-Estacionamiento",
"sfc":"17",
"cpt":"0,190000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0010",
"cc1":"W",
"cc2":"U"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"SM",
"pu":"08"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Almacen-Estacionamiento",
"sfc":"8",
"cpt":"0,210000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0011",
"cc1":"E",
"cc2":"I"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"SM",
"pu":"09"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Almacen-Estacionamiento",
"sfc":"5",
"cpt":"0,190000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0012",
"cc1":"R",
"cc2":"O"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"SM",
"pu":"10"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Almacen-Estacionamiento",
"sfc":"7",
"cpt":"0,210000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0013",
"cc1":"T",
"cc2":"P"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"SM",
"pu":"11"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Almacen-Estacionamiento",
"sfc":"7",
"cpt":"0,210000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0014",
"cc1":"Y",
"cc2":"A"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"00",
"pu":"01"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"65",
"cpt":"2,270000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0015",
"cc1":"U",
"cc2":"S"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"00",
"pu":"02"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"80",
"cpt":"2,050000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0016",
"cc1":"I",
"cc2":"D"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"00",
"pu":"03"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"78",
"cpt":"2,190000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0017",
"cc1":"O",
"cc2":"F"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"01",
"pu":"01"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0018",
"cc1":"P",
"cc2":"G"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"01",
"pu":"02"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0019",
"cc1":"A",
"cc2":"H"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"01",
"pu":"03"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0020",
"cc1":"O",
"cc2":"F"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"01",
"pu":"04"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0021",
"cc1":"P",
"cc2":"G"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"02",
"pu":"01"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0022",
"cc1":"A",
"cc2":"H"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"02",
"pu":"02"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0023",
"cc1":"S",
"cc2":"J"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"02",
"pu":"03"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0024",
"cc1":"D",
"cc2":"K"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"02",
"pu":"04"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0025",
"cc1":"F",
"cc2":"L"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"03",
"pu":"01"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0026",
"cc1":"G",
"cc2":"B"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"03",
"pu":"02"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0027",
"cc1":"H",
"cc2":"Z"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"03",
"pu":"03"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0028",
"cc1":"J",
"cc2":"X"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"03",
"pu":"04"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0029",
"cc1":"K",
"cc2":"M"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"04",
"pu":"01"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0030",
"cc1":"H",
"cc2":"Z"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"04",
"pu":"02"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0031",
"cc1":"J",
"cc2":"X"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"04",
"pu":"03"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0032",
"cc1":"K",
"cc2":"M"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"04",
"pu":"04"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0033",
"cc1":"L",
"cc2":"Q"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"06",
"pu":"02"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0034",
"cc1":"B",
"cc2":"W"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"05",
"pu":"01"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0035",
"cc1":"Z",
"cc2":"E"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"05",
"pu":"02"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0036",
"cc1":"X",
"cc2":"R"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"05",
"pu":"03"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0037",
"cc1":"M",
"cc2":"T"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"05",
"pu":"04"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0038",
"cc1":"Q",
"cc2":"Y"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"06",
"pu":"01"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0039",
"cc1":"W",
"cc2":"U"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"06",
"pu":"03"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0040",
"cc1":"M",
"cc2":"T"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"06",
"pu":"04"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0041",
"cc1":"Q",
"cc2":"Y"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"07",
"pu":"01"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0042",
"cc1":"W",
"cc2":"U"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"07",
"pu":"02"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0043",
"cc1":"E",
"cc2":"I"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"07",
"pu":"03"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0044",
"cc1":"R",
"cc2":"O"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"07",
"pu":"04"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0045",
"cc1":"T",
"cc2":"P"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"08",
"pu":"01"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0046",
"cc1":"Y",
"cc2":"A"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"08",
"pu":"02"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0047",
"cc1":"U",
"cc2":"S"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"08",
"pu":"03"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0048",
"cc1":"I",
"cc2":"D"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"08",
"pu":"04"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0049",
"cc1":"O",
"cc2":"F"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"09",
"pu":"01"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0050",
"cc1":"U",
"cc2":"S"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"09",
"pu":"02"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0051",
"cc1":"I",
"cc2":"D"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"09",
"pu":"03"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"72",
"cpt":"2,330000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0052",
"cc1":"O",
"cc2":"F"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4",
"snp":"0"},
"loint":{"es":"E",
"pt":"09",
"pu":"04"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"81",
"cpt":"2,450000",
"ant":"1976"}},
{"rc":{"pc1":"9366108",
"pc2":"VK2696N",
"car":"0053",
"cc1":"P",
"cc2":"G"},
"dt":{"loine":{"cp":"28",
"cm":"7"},
"cmc":"7",
"np":"MADRID",
"nm":"ALCORCON",
"locs":{"lous":{"lourb":{"dir":{"cv":"391",
"tv":"CL",
"nv":"SIETE OJOS",
"pnp":"4"},
"loint":{"es":"E",
"pt":"00",
"pu":"04"},
"dp":"28922",
"dm":"4"}}}},
"debi":{"luso":"Residencial",
"sfc":"49",
"cpt":"1,430000",
"ant":"1976"}}]}}}'::jsonb as bruto),
     piso as (
       select j.bruto, e as f
         from j, jsonb_array_elements(j.bruto->'consulta_dnprcResult'->'lrcdnp'->'rcdnp') e
     )
insert into ficha_catastro
  (referencia, municipio, provincia, cp, anio, inmuebles, viviendas, superficie,
   plantas, usos, tipo_via, nombre_via, numero, codigo_via, distrito_municipal,
   ine_provincia, ine_municipio, bruto, consultado_en, actualizado_en)
select '9366108VK2696N',
       min(f->'dt'->>'nm'),
       min(f->'dt'->>'np'),
       min(f->'dt'->'locs'->'lous'->'lourb'->>'dp'),
       min(replace(f->'debi'->>'ant', '.', ''))::int,
       count(*),
       count(*) filter (where f->'debi'->>'luso' = 'Residencial'),
       sum(coalesce(replace(f->'debi'->>'sfc', '.', '')::int, 0)),
       (select array_agg(distinct pt order by pt)
          from piso p2,
               lateral (select p2.f->'dt'->'locs'->'lous'->'lourb'->'loint'->>'pt' as pt) z
         where pt is not null),
       (select jsonb_object_agg(uso, n)
          from (select p3.f->'debi'->>'luso' as uso, count(*) as n from piso p3 group by 1) w),
       min(f->'dt'->'locs'->'lous'->'lourb'->'dir'->>'tv'),
       min(f->'dt'->'locs'->'lous'->'lourb'->'dir'->>'nv'),
       min(f->'dt'->'locs'->'lous'->'lourb'->'dir'->>'pnp'),
       min(f->'dt'->'locs'->'lous'->'lourb'->'dir'->>'cv'),
       min(f->'dt'->'locs'->'lous'->'lourb'->>'dm'),
       min(f->'dt'->'loine'->>'cp'),
       min(f->'dt'->'loine'->>'cm'),
       -- Y el bruto entero. NO vale `min(bruto)`: Postgres no tiene min() para
       -- jsonb y da "function min(jsonb) does not exist". Se coge del CTE.
       (select bruto from j),
       now(), now()
  from piso
on conflict (referencia) do nothing;

-- ---------------------------------------------------------------------------
-- CL MERCEDES IZQUIERDO 3, SAN SEBASTIAN DE LOS REYES
-- ---------------------------------------------------------------------------

with j as (select '{"consulta_dnprcResult":{"control":{"cudnp":10},
"lrcdnp":{"rcdnp":[{"rc":{"pc1":"7091107",
"pc2":"VK4879S",
"car":"0001",
"cc1":"L",
"cc2":"J"},
"dt":{"loine":{"cp":"28",
"cm":"134"},
"cmc":"134",
"np":"MADRID",
"nm":"SAN SEBASTIAN DE LOS REYES",
"locs":{"lous":{"lourb":{"dir":{"cv":"242",
"tv":"CL",
"nv":"MERCEDES IZQUIERDO",
"pnp":"3",
"snp":"0"},
"loint":{"pt":"00",
"pu":"A"},
"dp":"28701",
"dm":"1"}}}},
"debi":{"luso":"Comercial",
"sfc":"98",
"cpt":"9,660000",
"ant":"1973"}},
{"rc":{"pc1":"7091107",
"pc2":"VK4879S",
"car":"0002",
"cc1":"B",
"cc2":"K"},
"dt":{"loine":{"cp":"28",
"cm":"134"},
"cmc":"134",
"np":"MADRID",
"nm":"SAN SEBASTIAN DE LOS REYES",
"locs":{"lous":{"lourb":{"dir":{"cv":"242",
"tv":"CL",
"nv":"MERCEDES IZQUIERDO",
"pnp":"3",
"snp":"0"},
"loint":{"pt":"00",
"pu":"B"},
"dp":"28701",
"dm":"1"}}}},
"debi":{"luso":"Comercial",
"sfc":"121",
"cpt":"12,940000",
"ant":"1973"}},
{"rc":{"pc1":"7091107",
"pc2":"VK4879S",
"car":"0003",
"cc1":"Z",
"cc2":"L"},
"dt":{"loine":{"cp":"28",
"cm":"134"},
"cmc":"134",
"np":"MADRID",
"nm":"SAN SEBASTIAN DE LOS REYES",
"locs":{"lous":{"lourb":{"dir":{"cv":"242",
"tv":"CL",
"nv":"MERCEDES IZQUIERDO",
"pnp":"3",
"snp":"0"},
"loint":{"pt":"01",
"pu":"A"},
"dp":"28701",
"dm":"1"}}}},
"debi":{"luso":"Residencial",
"sfc":"93",
"cpt":"9,840000",
"ant":"1973"}},
{"rc":{"pc1":"7091107",
"pc2":"VK4879S",
"car":"0004",
"cc1":"X",
"cc2":"B"},
"dt":{"loine":{"cp":"28",
"cm":"134"},
"cmc":"134",
"np":"MADRID",
"nm":"SAN SEBASTIAN DE LOS REYES",
"locs":{"lous":{"lourb":{"dir":{"cv":"242",
"tv":"CL",
"nv":"MERCEDES IZQUIERDO",
"pnp":"3",
"snp":"0"},
"loint":{"pt":"01",
"pu":"B"},
"dp":"28701",
"dm":"1"}}}},
"debi":{"luso":"Residencial",
"sfc":"88",
"cpt":"9,510000",
"ant":"1973"}},
{"rc":{"pc1":"7091107",
"pc2":"VK4879S",
"car":"0005",
"cc1":"M",
"cc2":"Z"},
"dt":{"loine":{"cp":"28",
"cm":"134"},
"cmc":"134",
"np":"MADRID",
"nm":"SAN SEBASTIAN DE LOS REYES",
"locs":{"lous":{"lourb":{"dir":{"cv":"242",
"tv":"CL",
"nv":"MERCEDES IZQUIERDO",
"pnp":"3",
"snp":"0"},
"loint":{"pt":"02",
"pu":"A"},
"dp":"28701",
"dm":"1"}}}},
"debi":{"luso":"Residencial",
"sfc":"93",
"cpt":"9,840000",
"ant":"1973"}},
{"rc":{"pc1":"7091107",
"pc2":"VK4879S",
"car":"0006",
"cc1":"Q",
"cc2":"X"},
"dt":{"loine":{"cp":"28",
"cm":"134"},
"cmc":"134",
"np":"MADRID",
"nm":"SAN SEBASTIAN DE LOS REYES",
"locs":{"lous":{"lourb":{"dir":{"cv":"242",
"tv":"CL",
"nv":"MERCEDES IZQUIERDO",
"pnp":"3",
"snp":"0"},
"loint":{"pt":"02",
"pu":"B"},
"dp":"28701",
"dm":"1"}}}},
"debi":{"luso":"Residencial",
"sfc":"88",
"cpt":"9,510000",
"ant":"1973"}},
{"rc":{"pc1":"7091107",
"pc2":"VK4879S",
"car":"0007",
"cc1":"W",
"cc2":"M"},
"dt":{"loine":{"cp":"28",
"cm":"134"},
"cmc":"134",
"np":"MADRID",
"nm":"SAN SEBASTIAN DE LOS REYES",
"locs":{"lous":{"lourb":{"dir":{"cv":"242",
"tv":"CL",
"nv":"MERCEDES IZQUIERDO",
"pnp":"3",
"snp":"0"},
"loint":{"pt":"03",
"pu":"A"},
"dp":"28701",
"dm":"1"}}}},
"debi":{"luso":"Residencial",
"sfc":"93",
"cpt":"9,840000",
"ant":"1973"}},
{"rc":{"pc1":"7091107",
"pc2":"VK4879S",
"car":"0008",
"cc1":"E",
"cc2":"Q"},
"dt":{"loine":{"cp":"28",
"cm":"134"},
"cmc":"134",
"np":"MADRID",
"nm":"SAN SEBASTIAN DE LOS REYES",
"locs":{"lous":{"lourb":{"dir":{"cv":"242",
"tv":"CL",
"nv":"MERCEDES IZQUIERDO",
"pnp":"3",
"snp":"0"},
"loint":{"pt":"03",
"pu":"B"},
"dp":"28701",
"dm":"1"}}}},
"debi":{"luso":"Residencial",
"sfc":"88",
"cpt":"9,510000",
"ant":"1973"}},
{"rc":{"pc1":"7091107",
"pc2":"VK4879S",
"car":"0009",
"cc1":"R",
"cc2":"W"},
"dt":{"loine":{"cp":"28",
"cm":"134"},
"cmc":"134",
"np":"MADRID",
"nm":"SAN SEBASTIAN DE LOS REYES",
"locs":{"lous":{"lourb":{"dir":{"cv":"242",
"tv":"CL",
"nv":"MERCEDES IZQUIERDO",
"pnp":"3",
"snp":"0"},
"loint":{"pt":"04",
"pu":"A"},
"dp":"28701",
"dm":"1"}}}},
"debi":{"luso":"Residencial",
"sfc":"93",
"cpt":"9,840000",
"ant":"1973"}},
{"rc":{"pc1":"7091107",
"pc2":"VK4879S",
"car":"0010",
"cc1":"W",
"cc2":"M"},
"dt":{"loine":{"cp":"28",
"cm":"134"},
"cmc":"134",
"np":"MADRID",
"nm":"SAN SEBASTIAN DE LOS REYES",
"locs":{"lous":{"lourb":{"dir":{"cv":"242",
"tv":"CL",
"nv":"MERCEDES IZQUIERDO",
"pnp":"3",
"snp":"0"},
"loint":{"pt":"04",
"pu":"B"},
"dp":"28701",
"dm":"1"}}}},
"debi":{"luso":"Residencial",
"sfc":"88",
"cpt":"9,510000",
"ant":"1973"}}]}}}'::jsonb as bruto),
     piso as (
       select j.bruto, e as f
         from j, jsonb_array_elements(j.bruto->'consulta_dnprcResult'->'lrcdnp'->'rcdnp') e
     )
insert into ficha_catastro
  (referencia, municipio, provincia, cp, anio, inmuebles, viviendas, superficie,
   plantas, usos, tipo_via, nombre_via, numero, codigo_via, distrito_municipal,
   ine_provincia, ine_municipio, bruto, consultado_en, actualizado_en)
select '7091107VK4879S',
       min(f->'dt'->>'nm'),
       min(f->'dt'->>'np'),
       min(f->'dt'->'locs'->'lous'->'lourb'->>'dp'),
       min(replace(f->'debi'->>'ant', '.', ''))::int,
       count(*),
       count(*) filter (where f->'debi'->>'luso' = 'Residencial'),
       sum(coalesce(replace(f->'debi'->>'sfc', '.', '')::int, 0)),
       (select array_agg(distinct pt order by pt)
          from piso p2,
               lateral (select p2.f->'dt'->'locs'->'lous'->'lourb'->'loint'->>'pt' as pt) z
         where pt is not null),
       (select jsonb_object_agg(uso, n)
          from (select p3.f->'debi'->>'luso' as uso, count(*) as n from piso p3 group by 1) w),
       min(f->'dt'->'locs'->'lous'->'lourb'->'dir'->>'tv'),
       min(f->'dt'->'locs'->'lous'->'lourb'->'dir'->>'nv'),
       min(f->'dt'->'locs'->'lous'->'lourb'->'dir'->>'pnp'),
       min(f->'dt'->'locs'->'lous'->'lourb'->'dir'->>'cv'),
       min(f->'dt'->'locs'->'lous'->'lourb'->>'dm'),
       min(f->'dt'->'loine'->>'cp'),
       min(f->'dt'->'loine'->>'cm'),
       -- Y el bruto entero. NO vale `min(bruto)`: Postgres no tiene min() para
       -- jsonb y da "function min(jsonb) does not exist". Se coge del CTE.
       (select bruto from j),
       now(), now()
  from piso
on conflict (referencia) do nothing;

-- ---------------------------------------------------------------------------
-- Sus portales, desde el bruto que acabamos de guardar
-- ---------------------------------------------------------------------------
--
-- Se agrupa por (calle, numero CON SU LETRA si la tuviera, escalera), que es la
-- identidad del portal segun Catastro. Ninguna de estas dos tiene letra, pero se
-- escribe bien desde el principio para no repetir el fallo del parser.

with piso as (
  select f.id as ficha_id,
         e->'dt'->'locs'->'lous'->'lourb'->'dir'->>'tv' as tv,
         e->'dt'->'locs'->'lous'->'lourb'->'dir'->>'nv' as nv,
         (e->'dt'->'locs'->'lous'->'lourb'->'dir'->>'pnp')
           || coalesce('(' || (e->'dt'->'locs'->'lous'->'lourb'->'dir'->>'plp') || ')', '') as num,
         coalesce(e->'dt'->'locs'->'lous'->'lourb'->'loint'->>'es', '') as esc,
         coalesce(e->'dt'->'locs'->'lous'->'lourb'->'loint'->>'pt', '') as pt,
         e->'debi'->>'luso' as uso,
         coalesce(replace(e->'debi'->>'sfc', '.', '')::int, 0) as sfc
    from ficha_catastro f,
         jsonb_array_elements(f.bruto->'consulta_dnprcResult'->'lrcdnp'->'rcdnp') e
   where f.referencia in ('9366108VK2696N', '7091107VK4879S')
),
por_uso as (
  select ficha_id, tv, nv, num, esc, uso, count(*) as n
    from piso
   group by 1, 2, 3, 4, 5, 6
)
insert into ficha_catastro_portal
  (ficha_id, tipo_via, nombre_via, numero, escalera,
   inmuebles, viviendas, superficie, plantas, usos)
select p.ficha_id, p.tv, p.nv, p.num, p.esc,
       count(*),
       count(*) filter (where p.uso = 'Residencial'),
       sum(p.sfc),
       array_remove(array_agg(distinct nullif(p.pt, '')), null),
       (select jsonb_object_agg(u.uso, u.n)
          from por_uso u
         where u.ficha_id = p.ficha_id and u.tv = p.tv and u.nv = p.nv
           and u.num = p.num and u.esc = p.esc)
  from piso p
 group by p.ficha_id, p.tv, p.nv, p.num, p.esc
on conflict (ficha_id, numero, escalera) do nothing;

-- ---------------------------------------------------------------------------
-- Sus inmuebles, uno por piso, con su portal apuntado
-- ---------------------------------------------------------------------------
--
-- `coeficiente` es el coeficiente de participacion, que Catastro escribe con coma
-- decimal ("0,220000"). La superficie viene con punto de millar ("1.431"). Las dos
-- cosas se arreglan antes de guardar.

insert into ficha_catastro_inmueble
  (ficha_id, portal_id, referencia, numero, escalera, planta, puerta, uso, superficie, coeficiente)
select f.id,
       p.id,
       (e->'rc'->>'pc1') || (e->'rc'->>'pc2') || (e->'rc'->>'car')
         || (e->'rc'->>'cc1') || (e->'rc'->>'cc2'),
       nullif(e->'dt'->'locs'->'lous'->'lourb'->'dir'->>'pnp', ''),
       nullif(coalesce(e->'dt'->'locs'->'lous'->'lourb'->'loint'->>'es', ''), ''),
       nullif(coalesce(e->'dt'->'locs'->'lous'->'lourb'->'loint'->>'pt', ''), ''),
       nullif(coalesce(e->'dt'->'locs'->'lous'->'lourb'->'loint'->>'pu', ''), ''),
       e->'debi'->>'luso',
       replace(e->'debi'->>'sfc', '.', '')::numeric,
       replace(replace(e->'debi'->>'cpt', '.', ''), ',', '.')::numeric
  from ficha_catastro f
  join lateral jsonb_array_elements(f.bruto->'consulta_dnprcResult'->'lrcdnp'->'rcdnp') e on true
  left join ficha_catastro_portal p
    on p.ficha_id = f.id
   and p.numero = (e->'dt'->'locs'->'lous'->'lourb'->'dir'->>'pnp')
                  || coalesce('(' || (e->'dt'->'locs'->'lous'->'lourb'->'dir'->>'plp') || ')', '')
   and coalesce(p.escalera, '') = coalesce(e->'dt'->'locs'->'lous'->'lourb'->'loint'->>'es', '')
 where f.referencia in ('9366108VK2696N', '7091107VK4879S')
on conflict (referencia) do nothing;

-- ---------------------------------------------------------------------------
-- Y los dos accesos se enlazan con la regla de siempre
-- ---------------------------------------------------------------------------

update accesos a
   set ficha_catastro_portal_id = (
         select p.id
           from ficha_catastro_portal p
          where coalesce(p.tipo_via, '')   = coalesce(a.tipo_via, '')
            and coalesce(p.nombre_via, '') = coalesce(a.nombre_via, '')
            and coalesce(p.numero, '')     = coalesce(a.numero, '')
            and coalesce(p.escalera, '')   = coalesce(a.escalera, '')
       )
 where a.ficha_catastro_portal_id is null
   and (
         select count(*)
           from ficha_catastro_portal p
          where coalesce(p.tipo_via, '')   = coalesce(a.tipo_via, '')
            and coalesce(p.nombre_via, '') = coalesce(a.nombre_via, '')
            and coalesce(p.numero, '')     = coalesce(a.numero, '')
            and coalesce(p.escalera, '')   = coalesce(a.escalera, '')
       ) = 1;

-- ---------------------------------------------------------------------------
-- Que diga lo que ha hecho
-- ---------------------------------------------------------------------------
--
-- Arriba: las dos fichas, con un portal cada una, 53 y 10 pisos, y su acceso
-- enlazado. Abajo: 2.530 / 2.530 / 0.

select f.referencia,
       f.municipio,
       p.tipo_via || ' ' || p.nombre_via || ' ' || p.numero
         || coalesce(' esc ' || nullif(p.escalera, ''), '') as el_portal,
       p.inmuebles,
       p.viviendas,
       p.superficie,
       p.usos::text,
       (select count(*) from ficha_catastro_inmueble i where i.portal_id = p.id) as pisos_apuntando,
       (select count(*) from accesos a where a.ficha_catastro_portal_id = p.id)  as accesos_enlazados
  from ficha_catastro f
  join ficha_catastro_portal p on p.ficha_id = f.id
 where f.referencia in ('9366108VK2696N', '7091107VK4879S');

select count(*)                        as accesos,
       count(ficha_catastro_portal_id) as enlazados,
       count(*) - count(ficha_catastro_portal_id) as sin_enlazar
  from accesos;
